### ISSUE TITLE
Wallet panic after mined several blocks

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer-wallet#127]
Wallet panic right after started. We are using 0.10 dev branch, testnet. Just mined several blocks, and the wallet got panic. The command line we use is  './qitmeer-wallet web'

>web model
2021-10-08|15:52:42.319 [INFO ] Established connection to RPC server 127.0.0.1:18131 module=RPCCLI
2021-10-08|15:52:42.321 [INFO ] notification rescan block           start=23170 end=23345
panic: runtime error: index out of range [0] with length 0

goroutine 26 [running]:
github.com/Qitmeer/qitmeer-wallet/wallet.(*Wallet).parseTxDetail(0xc0000b0000, 0x0, 0x0, 0xc00022a2c0, 0x40, 0xc00022a300, 0x40, 0x100000000, 0x0, 0xc0001b0860, ...)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/wallet/wallet.go:1165 +0xd49
github.com/Qitmeer/qitmeer-wallet/wallet.(*Wallet).parseTx(0xc0000b0000, 0xc000098d20, 0xd14c80, 0xc000098d20, 0x16, 0x0, 0x0, 0xc000228a78, 0x16, 0x1, ...)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/wallet/wallet.go:1080 +0x253
github.com/Qitmeer/qitmeer-wallet/wallet.(*Wallet).OnTxAcceptedVerbose(0xc0000b0000, 0xc00049a2c0, 0xc000098d20)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/wallet/wallet.go:1409 +0x69
github.com/Qitmeer/qitmeer/rpc/client.(*Client).handleNotification(0xc00049a2c0, 0xc0001fbf80)
        /home/ray/go/pkg/mod/github.com/!qitmeer/qitmeer@v0.10.1/rpc/client/client.go:364 +0xe2d
github.com/Qitmeer/qitmeer/rpc/client.(*Client).handleMessage(0xc00049a2c0, 0xc00022c600, 0x3bd, 0x600)
        /home/ray/go/pkg/mod/github.com/!qitmeer/qitmeer@v0.10.1/rpc/client/client.go:225 +0x698
github.com/Qitmeer/qitmeer/rpc/client.(*Client).wsInHandler(0xc00049a2c0)
        /home/ray/go/pkg/mod/github.com/!qitmeer/qitmeer@v0.10.1/rpc/client/client.go:185 +0x45
created by github.com/Qitmeer/qitmeer/rpc/client.(*Client).start
        /home/ray/go/pkg/mod/github.com/!qitmeer/qitmeer@v0.10.1/rpc/client/client.go:90 +0x189

**Comment by rlinxy** [comment]
Just tried delete the wallet db and created/imported seed, now the wallet is working fine. How ever I still got error when tring to get account balance, the command line I use is './qitmeer-wallet qc listaccountsbalance' 

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb17dba]

goroutine 1 [running]:
github.com/Qitmeer/qitmeer-wallet/wallet.(*Wallet).AccountBalances(0xc0005de000, 0x2c, 0x20, 0x18, 0xdafcc0, 0xd38960, 0x108fe20)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/wallet/wallet.go:1759 +0x3da
github.com/Qitmeer/qitmeer-wallet/rpc/walletrpc.ListAccounts(...)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/rpc/walletrpc/methods.go:47
github.com/Qitmeer/qitmeer-wallet/commands.listAccountsBalance.func1(0x0, 0x0, 0xc0005de000, 0xcb415f, 0xc0005cc000, 0x0, 0x6)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/commands/console.go:199 +0x3b
github.com/Qitmeer/qitmeer-wallet/commands.(*JsonCmdHelper).Call(0xc0005bc1c0, 0xc0005bc1c0, 0x14, 0xe590ec, 0x7)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/commands/commands.go:33 +0x5c
github.com/Qitmeer/qitmeer-wallet/commands.listAccountsBalance(0x0, 0x0, 0x0, 0x0)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/commands/console.go:202 +0x5a
github.com/Qitmeer/qitmeer-wallet/commands.newListAccountsBalance.func1(0xc0005ac280, 0x15ac220, 0x0, 0x0, 0x0, 0x0)
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/commands/qc.go:408 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc0005ac280, 0x15ac220, 0x0, 0x0, 0xc0005ac280, 0x15ac220)
        /home/ray/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x1566900, 0x407f85, 0xc000082058, 0x0)
        /home/ray/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ray/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/ray/meer/wallet/qitmeer-wallet-0.10-dev/main.go:10 +0x31
