### ISSUE TITLE
txlist (交易记录查询) on wallet web model does not work

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-wallet#30]
The transaction displayed by qitmeer wallet web does not work, as shown below: 

![image](https://user-images.githubusercontent.com/32875657/86240869-82320b00-bbd4-11ea-8616-2d75192a5894.png)

The transaction displayed does not exist and the latest generated transaction will not be displayed.

**Comment by blocklee** [comment]
https://github.com/Qitmeer/qitmeer-wallet/blob/master/assets/src/src/components/txlist.vue

 txid is used in the code of txlist.vue, not txhash, maybe that's the problem.

```
<el-main class="cmain"> 
 <el-table :data="txList"> 
 <el-table-column prop="txId" label="txId" width="470"></el-table-column> 
 <el-table-column prop="type" label="in/out" width="60"></el-table-column> 
 <el-table-column prop="amount" label="金额"></el-table-column> 
 </el-table> 
 </el-main> 
```

**Comment by dindinw** [comment]
The issue has been fixed by https://github.com/Qitmeer/qitmeer-wallet/pull/28 please use the latest code. Please also make sure to use `make` to build a whole project to let `qitmeer-wallet`s web module's work with the latest updates.

**Comment by blocklee** [comment]
I have get the latest code.

```
D:\git\qitmeer-wallet>git pull
Already up to date.

D:\git\qitmeer-wallet>make
go get github.com/rakyll/statik
if [ ! -d assets/src/node_modules/ ]; then \
        cd assets/src && npm install; \
fi
cd assets/src && npm run build

> qitmeer-wallet-ui@0.0.1 build D:\git\qitmeer-wallet\assets\src
> vue-cli-service build


\  Building for production...

 WARNING  Compiled with 3 warnings                                                                    10:13:02 ├F10: PM┤

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  assets/js/chunk-vendors.8515a414.js (832 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.1 MiB)
      assets/css/chunk-vendors.364ef837.css
      assets/js/chunk-vendors.8515a414.js
      assets/css/app.5667424b.css
      assets/js/app.31a673ac.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                      Size             Gzipped

  dist\assets\js\chunk-vendors.8515a414.    832.26 KiB       222.03 KiB
  js
  dist\assets\js\app.31a673ac.js            42.87 KiB        8.88 KiB
  dist\config.js                            0.11 KiB         0.11 KiB
  dist\assets\css\chunk-vendors.364ef837    227.82 KiB       34.58 KiB
  .css
  dist\assets\css\app.5667424b.css          21.59 KiB        7.51 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

cd assets/statik && rm -fr statik.go
cd assets && statik -src ./src/dist/
go build

D:\git\qitmeer-wallet>qitmeer-wallet.exe qc web
web model
update blcok:22429/22429
succ
update blcok:22429/22429
succ
````

![image](https://user-images.githubusercontent.com/32875657/86254484-6df80900-bbe8-11ea-953a-44b5fb2d27a9.png)

**Comment by dindinw** [comment]
The TxId showed in your screen shoot has already worked  https://explorer.qitmeer.io/tx/87660967c7890b82174af1432aefde533e0c277a1034b140f043e4974469dac2
So what's your problem?

**Comment by blocklee** [comment]
My compilation process is very strange. The first time I make it, an error will be reported and the compilation cannot be completed. When I make the second time, it shows that the compilation is completed. But I don't know if it's really a success.

- the first time

```bash
D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet>make
go get github.com/rakyll/statik
if [ ! -d assets/src/node_modules/ ]; then \
        cd assets/src && npm install; \
fi
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> yorkie@2.0.0 install D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.14.1 install D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-72_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@2.6.11 postinstall D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@4.14.1 postinstall D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-sass
> node scripts/build.js

Building: E:\Program Files (x86)\node.exe D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'E:\\Program Files (x86)\\node.exe',
gyp verb cli   'D:\\git\\test-sh\\medina2.0\\pc-wallet\\qitmeer-wallet\\assets\\src\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.18.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\Program Files (x86)\\node.exe" "D:\\git\\test-sh\\medina2.0\\pc-wallet\\qitmeer-wallet\\assets\\src\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\node_modules\node-sass
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-07-02T02_26_44_953Z-debug.log
make: *** [Makefile:11: npm] Error 1
```


- the second time

```bash
D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet>
D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet>make
go get github.com/rakyll/statik
if [ ! -d assets/src/node_modules/ ]; then \
        cd assets/src && npm install; \
fi
cd assets/src && npm run build

> qitmeer-wallet-ui@0.0.1 build D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src
> vue-cli-service build


/  Building for production...

 WARNING  Compiled with 13 warnings                                                                   10:29:29 ├F10: AM┤

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'action' is defined but never used (no-unused-vars) at src\components\node.vue:76:22:
  74 |           closeOnPressEscape: false,
  75 |           confirmButtonText: "确定",
> 76 |           callback: (action, instance) => {
     |                      ^
  77 |             _this.$emit("getQitmeerdList", () => {
  78 |               _this.tableData = _this.$store.state.QitmeerdList;
  79 |             });


error: 'instance' is defined but never used (no-unused-vars) at src\components\node.vue:76:30:
  74 |           closeOnPressEscape: false,
  75 |           confirmButtonText: "确定",
> 76 |           callback: (action, instance) => {
     |                              ^
  77 |             _this.$emit("getQitmeerdList", () => {
  78 |               _this.tableData = _this.$store.state.QitmeerdList;
  79 |             });


2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'action' is defined but never used (no-unused-vars) at src\components\nodenew.vue:141:22:
  139 |           closeOnPressEscape: false,
  140 |           confirmButtonText: "确定",
> 141 |           callback: (action, instance) => {
      |                      ^
  142 |             this.$router.push({ path: "/node" });
  143 |           }
  144 |         });


error: 'instance' is defined but never used (no-unused-vars) at src\components\nodenew.vue:141:30:
  139 |           closeOnPressEscape: false,
  140 |           confirmButtonText: "确定",
> 141 |           callback: (action, instance) => {
      |                              ^
  142 |             this.$router.push({ path: "/node" });
  143 |           }
  144 |         });


2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'action' is defined but never used (no-unused-vars) at src\components\walletcreate.vue:122:23:
  120 |             showClose: false,
  121 |             confirmButtonText: "确定",
> 122 |             callback: action => {}
      |                       ^
  123 |           });
  124 |         } else {
  125 |           this.ruleForm.seed = response.data.result.seed;


error: 'formName' is defined but never used (no-unused-vars) at src\components\walletcreate.vue:130:16:
  128 |       });
  129 |     },
> 130 |     submitForm(formName) {
      |                ^
  131 |       let _this = this;
  132 |       this.$refs.ruleForm.validate(valid => {
  133 |         if (!valid) {


2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'formName' is defined but never used (no-unused-vars) at src\components\accountnew.vue:60:16:
  58 |   },
  59 |   methods: {
> 60 |     submitForm(formName) {
     |                ^
  61 |       let _this = this;
  62 |       this.$refs.ruleForm.validate(valid => {
  63 |         if (!valid) {


error: Parsing error: control-character-in-input-stream (vue/no-parsing-error) at src\components\accountnew.vue:81:23:
  79 |             return;
  80 |           }
> 81 |           this.$alert(创建账号成功", {
     |                       ^
  82 |             showClose: false,
  83 |             closeOnClickModal: false,
  84 |             closeOnPressEscape: false,


error: 'action' is defined but never used (no-unused-vars) at src\components\accountnew.vue:86:24:
  84 |             closeOnPressEscape: false,
  85 |             confirmButtonText: "确定",
> 86 |             callback: (action, instance) => {
     |                        ^
  87 |               this.$router.push({ path: "/account" });
  88 |             }
  89 |           });


error: 'instance' is defined but never used (no-unused-vars) at src\components\accountnew.vue:86:32:
  84 |             closeOnPressEscape: false,
  85 |             confirmButtonText: "确定",
> 86 |             callback: (action, instance) => {
     |                                ^
  87 |               this.$router.push({ path: "/account" });
  88 |             }
  89 |           });


4 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'h' is assigned a value but never used (no-unused-vars) at src\components\txsend.vue:107:15:
  105 |         })
  106 |       }).then(response => {
> 107 |         const h = this.$createElement;
      |               ^
  108 |         if (typeof response.data.error != "undefined") {
  109 |           _this.$emit("alertResError", response.data.error, () => {});
  110 |           return;


error: Parsing error: control-character-in-input-stream (vue/no-parsing-error) at src\components\txsend.vue:112:21:
  110 |           return;
  111 |         }
> 112 |         this.$alert(发送交易成功", {
      |                     ^
  113 |           showClose: false,
  114 |           closeOnClickModal: false,
  115 |           closeOnPressEscape: false,


error: 'action' is defined but never used (no-unused-vars) at src\components\txsend.vue:117:22:
  115 |           closeOnPressEscape: false,
  116 |           confirmButtonText: "确定",
> 117 |           callback: (action, instance) => {
      |                      ^
  118 |             this.$router.push({ path: "/tx/list" });
  119 |           }
  120 |         });


error: 'instance' is defined but never used (no-unused-vars) at src\components\txsend.vue:117:30:
  115 |           closeOnPressEscape: false,
  116 |           confirmButtonText: "确定",
> 117 |           callback: (action, instance) => {
      |                              ^
  118 |             this.$router.push({ path: "/tx/list" });
  119 |           }
  120 |         });


4 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: control-character-in-input-stream (vue/no-parsing-error) at src\components\importkey.vue:84:23:
  82 |             return;
  83 |           }
> 84 |           this.$alert(导入私钥成功", {
     |                       ^
  85 |             showClose: false,
  86 |             closeOnClickModal: false,
  87 |             closeOnPressEscape: false,


error: 'action' is defined but never used (no-unused-vars) at src\components\importkey.vue:89:24:
  87 |             closeOnPressEscape: false,
  88 |             confirmButtonText: "确定",
> 89 |             callback: (action, instance) => {
     |                        ^
  90 |               this.$router.push({ path: "/backup" });
  91 |             }
  92 |           });


error: 'instance' is defined but never used (no-unused-vars) at src\components\importkey.vue:89:32:
  87 |             closeOnPressEscape: false,
  88 |             confirmButtonText: "确定",
> 89 |             callback: (action, instance) => {
     |                                ^
  90 |               this.$router.push({ path: "/backup" });
  91 |             }
  92 |           });


3 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: control-character-in-input-stream (vue/no-parsing-error) at src\components\walletrecover.vue:131:22:
  129 |           }
  130 |           this.$message({
> 131 |             message: 恢复成功成功!",
      |                      ^
  132 |             type: "success",
  133 |             duration: 1000,
  134 |             onClose: function() {


error: 'action' is defined but never used (no-unused-vars) at src\components\walletrecover.vue:136:45:
  134 |             onClose: function() {
  135 |               _this.$emit("setLoading", false, "");
> 136 |               _this.$emit("getWalletStats", action => {
      |                                             ^
  137 |                 _this.$router.push("/");
  138 |               });
  139 |             }


2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Unexpected console statement (no-console) at src\App.vue:271:9:
  269 |           return;
  270 |         }
> 271 |         console.log("open wallet ok!");
      |         ^
  272 |         this.$router.push("/");
  273 |       });
  274 |     },


error: 'instance' is defined but never used (no-unused-vars) at src\App.vue:283:28:
  281 |         confirmButtonText: "创建新钱包",
  282 |         cancelButtonText: "恢复钱包",
> 283 |         callback: (action, instance) => {
      |                            ^
  284 |           if (action == "cancel") {
  285 |             _this.$router.push({ path: "/wallet/recover" });
  286 |           } else {


error: Unexpected console statement (no-console) at src\App.vue:486:13:
  484 |
  485 |           if (typeof response.data.error != "undefined") {
> 486 |             console.log(response.data.error);
      |             ^
  487 |             _this.qitmeerdStatusAlert = _this.$message({
  488 |               message: "获取节点信息异常! msg:" + response.data.error.message,
  489 |               type: "warning",


3 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Unexpected console statement (no-console) at src\components\txlist.vue:107:9:
  105 |           }
  106 |         }
> 107 |         console.log(findAddr);
      |         ^
  108 |
  109 |         tmpTable.push({
  110 |           date: "",


error: Unexpected console statement (no-console) at src\components\txlist.vue:116:7:
  114 |         });
  115 |       }
> 116 |       console.log(tmpTable);
      |       ^
  117 |       _this.txList = tmpTable;
  118 |     },
  119 |     getTxList(addr) {


2 errors found.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  in ./src/main.js

Module Warning (from ./node_modules/thread-loader/dist/cjs.js):

D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet\assets\src\src\main.js
  29:3  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)


 @ multi ./src/main.js

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  assets/js/chunk-vendors.8515a414.js (832 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.1 MiB)
      assets/css/chunk-vendors.364ef837.css
      assets/js/chunk-vendors.8515a414.js
      assets/css/app.5667424b.css
      assets/js/app.c6aba095.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                      Size             Gzipped

  dist\assets\js\chunk-vendors.8515a414.    832.26 KiB       222.03 KiB
  js
  dist\assets\js\app.c6aba095.js            42.87 KiB        8.88 KiB
  dist\config.js                            0.11 KiB         0.11 KiB
  dist\assets\css\chunk-vendors.364ef837    227.82 KiB       34.58 KiB
  .css
  dist\assets\css\app.5667424b.css          21.59 KiB        7.51 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

cd assets/statik && rm -fr statik.go
cd assets && statik -src ./src/dist/
go build

D:\git\test-sh\medina2.0\pc-wallet\qitmeer-wallet>
```

**Comment by blocklee** [comment]
> The TxId showed in your screen shoot has already worked https://explorer.qitmeer.io/tx/87660967c7890b82174af1432aefde533e0c277a1034b140f043e4974469dac2
> So what's your problem?

The transactions in txlist do not exist, or they are not in the current version.

**Comment by forchain** [comment]
> > The TxId showed in your screen shoot has already worked https://explorer.qitmeer.io/tx/87660967c7890b82174af1432aefde533e0c277a1034b140f043e4974469dac2
> > So what's your problem?
> 
> The transactions in txlist do not exist, or they are not in the current version.

Tx already listed in your screen shot, what do you mean by 'NOT in the current version'?

**Comment by forchain** [comment]
> My compilation process is very strange. The first time I make it, an error will be reported and the compilation cannot be completed. When I make the second time, it shows that the compilation is completed. But I don't know if it's really a success.

I think it is a separate issue issue, investigate later

**Comment by dindinw** [comment]
@blocklee the display issue has been fixed, the issue closed, please open another issue if any other issue.
