### ISSUE TITLE
My wallet crashed when I ran the qitmeer wallet console for a long time

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-wallet#62]
My wallet crashed when I ran the qitmeer wallet console for a long time(more than a day).

```bash
update blcok:142636/142636
succ
update blcok:142637/142637
succ
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x5cea40]

goroutine 208952 [running]:
math/big.(*Int).Sign(...)
        c:/go/src/math/big/int.go:39
crypto/elliptic.(*CurveParams).addJacobian(0xc000052200, 0xc00014ab60, 0xc00014abc0, 0x0, 0xc0005f71c0, 0xc0005f71a0, 0xc0005f71e0, 0xc0005f7080, 0x1005f70a0, 0xc0005f70c0)
        c:/go/src/crypto/elliptic/elliptic.go:113 +0x90
crypto/elliptic.(*CurveParams).ScalarMult(0xc000052200, 0xc00014ab60, 0xc00014abc0, 0xc000078006, 0x42, 0x42, 0x6, 0x199)
        c:/go/src/crypto/elliptic/elliptic.go:260 +0x1ca
crypto/ecdsa.Verify(0xc00014ac00, 0xc0004b0780, 0x40, 0x40, 0xc00014b4a0, 0xc00014b4c0, 0x0)
        c:/go/src/crypto/ecdsa/ecdsa.go:264 +0x69e
crypto/tls.verifyHandshakeSignature(0xe3, 0xc7d640, 0xc00014ac00, 0x7, 0xc0004b0780, 0x40, 0x40, 0xc0004c6008, 0x8b, 0x98, ...)
        c:/go/src/crypto/tls/auth.go:101 +0x417
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc00008fdf8, 0x0, 0x0)
        c:/go/src/crypto/tls/handshake_client_tls13.go:466 +0x3f5
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc00008fdf8, 0xc000178360, 0x0)
        c:/go/src/crypto/tls/handshake_client_tls13.go:85 +0x1f5
crypto/tls.(*Conn).clientHandshake(0xc0002a8700, 0x0, 0x0)
        c:/go/src/crypto/tls/handshake_client.go:198 +0x4a5
crypto/tls.(*Conn).Handshake(0xc0002a8700, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1362 +0x132
net/http.(*persistConn).addTLS.func2(0x0, 0xc0002a8700, 0x0, 0xc0002c1080)
        c:/go/src/net/http/transport.go:1409 +0x49
created by net/http.(*persistConn).addTLS
        c:/go/src/net/http/transport.go:1405 +0x1b1

D:\git\qitmeer-wallet>
```

- qitmeer-wallet version:

```bash
qitmeer-wallet>git log
commit 09b9e044c1caaf589456bfd93173586e800df256 (HEAD -> master, origin/master, origin/HEAD)
Merge: 59c71ce 574f098
Author: Alex Wu
Date:   Sat Aug 1 08:40:53 2020 +0800
```

- node version:

```bash
qitmeer version 0.9.1+hotfix-release-6e0a73a (Go version go1.14.4)
```

**Comment by forchain** [comment]
unable to reproduce, I left cli running a week before and it is still alive.


wallet-cli:
update blcok:223160/2231603148/223160
succ

The call stack is not inside qitmeer-wallet, please update your golang version and try again. If reproduced, please activate this issue.
